[package]
name = "flow_arena"
version = "0.1.0"
authors = ["LighghtEeloo <eelooecho@163.com>"]
edition = "2018"
repository = "https://github.com/LighghtEeloo/flow.er"
# readme = "readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["serde1"]
serde1 = ["serde"]

[dependencies.serde]
version = "1"
features = ["derive"] 
optional = true

[dev-dependencies]
serde_json = "1"
