[package]
name = "flow_arena"
version = "0.3.0"
authors = ["LighghtEeloo <eelooecho@163.com>"]
edition = "2018"
description = "A HashMap managed Graph Model with ownership concept"
readme = "README.md"
repository = "https://github.com/LighghtEeloo/flow.er"
license-file = "../LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["serde1"]
serde1 = ["serde"]

[dependencies]
# indexmap = "1.6"

[dependencies.serde]
version = "1"
features = ["derive"] 
optional = true

[dev-dependencies]
serde_json = "1"
