[package]
name = "tracer-yew"
version = "0.2.4"
authors = ["LighghtEeloo <eelooecho@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# strum = "0.20"
# strum_macros = "0.20"
serde = "1"
serde_derive = "1"
serde_json = "1"


yew = { path = "C:\\Zix100\\Repo\\yew\\packages\\yew" }
yew-services = { path = "C:\\Zix100\\Repo\\yew\\packages\\yew-services" }
wasm-timer = "0.2.0"


