[package]
name = "flow_er"
version = "0.2.4"
authors = ["LighghtEeloo <eelooecho@163.com>"]
edition = "2018"
readme = "readme.md"
repository = "https://github.com/LighghtEeloo/flow.er"

[dependencies]
# strum = "0.20"
# strum_macros = "0.20"
rand = { version = "0.7", features = ["wasm-bindgen"] }
serde = "1"
serde_json = "1"
wasm-timer = "0.2.0"
chrono = { version = "0.4", features = ["unstable-locales"] }


[dependencies.yew]
git = "https://github.com/yewstack/yew.git"
rev = "3740140"
package = "yew"

[dependencies.yew-services]
git = "https://github.com/yewstack/yew.git"
rev = "3740140"
package = "yew-services"


[workspace]
members = [
	"flow_arena",
	"flow_vessel",
	"flow_vase/flow_cli",
	# "flow_vase/flow_iced",
	# "flow_vase/flow_yew"
]

[dependencies.flow_cli]
path = "flow_vase/flow_cli"
