[package]
name = "flow_er"
version = "0.2.4"
authors = ["LighghtEeloo <eelooecho@163.com>"]
edition = "2018"
readme = "readme.md"
repository = "https://github.com/LighghtEeloo/flow.er"

[features]
cli = []
iced = []
yew = []

[workspace]
members = [
	"flow_arena",
	"flow_vessel",
	"flow_vase/flow_cli",
	# "flow_vase/flow_iced",
	"flow_vase/flow_yew",
	"flow_vase/flow_yew_dep",
]

[dependencies.flow_cli]
path = "flow_vase/flow_cli"

[dependencies.flow_yew]
path = "flow_vase/flow_yew"

[dependencies.flow_yew_dep]
path = "flow_vase/flow_yew_dep"
