[package]
name = "flow_er"
version = "0.2.4"
authors = ["LighghtEeloo <eelooecho@163.com>"]
edition = "2018"
readme = "readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# strum = "0.20"
# strum_macros = "0.20"
serde = "1"
serde_json = "1"


yew = { path = "C:\\Zix100\\Repo\\yew\\packages\\yew" }
yew-services = { path = "C:\\Zix100\\Repo\\yew\\packages\\yew-services" }
# yew = { path = "/home/lighght/Yggdrasill/Hof/Repo/yew/packages/yew" }
# yew-services = { path = "/home/lighght/Yggdrasill/Hof/Repo/yew/packages/yew-services" }

wasm-timer = "0.2.0"
chrono = { version = "0.4", features = ["unstable-locales"] }

