name: Rust

on:
  push:
    branches: [ dev, dev-Acc ]
  pull_request:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run flow_arena tests
      run: cargo test --package flow_arena
    - name: Run flow_vessel tests
      run: cargo test --package flow_vessel
    - name: Run flow_acc tests
      run: cargo test --package flow_acc
    - name: Run flow_cli tests
      run: cargo test --package flow_cli
    - name: Run tests
      run: cargo test --verbose
